name = "Hyde-A"
license = "MIT"
licenselink = "https://github.com/abhi1010/hyde-a/LICENSE"
description = "An elegant open source and mobile first theme, extended with new integrations and layout improvements"
homepage = "https://github.com/abhi1010/hyde-a"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]
min_version = 0.14

[author]
    name = "Abhishek Pandey"
    homepage = "http://abhi1010.github.io"

# If Porting existing theme
[original]
    author =  "poole"
    homepage = "http://hyde.getpoole.com"
    repo = "https://github.com/poole/hyde"
